Repository mantvydasdeltuva/kath, pull requests merged in 2024-12, with the labels that each got.

#5 MDE/README
  README.md
  docs/assets/genomika_logo_200.jpg
  docs/assets/genomika_logo_200.png
Labels: docs

#4 MDE/KFE-67
  app/front_end/src/features/editor/components/editorView/editorColumnMenu.tsx
  app/front_end/src/features/editor/components/editorView/editorColumnMenuAggregationItem.tsx
  app/front_end/src/features/editor/components/editorView/editorColumnMenuFilterItem.tsx
  app/front_end/src/features/editor/components/editorView/editorView.tsx
  app/front_end/src/features/editor/components/editorView/index.ts
Labels: feature

#7 MDE/KFE-70
  app/front_end/src/features/editor/components/editorView/editorColumnMenu.tsx
  app/front_end/src/features/editor/components/editorView/editorColumnMenuFilterItem.tsx
  app/front_end/src/features/editor/components/editorView/editorHeader.tsx
  app/front_end/src/features/editor/components/editorView/editorView.tsx
  app/front_end/src/features/editor/stores/workspaceContextProvider.tsx
  app/front_end/src/features/editor/types/index.ts
  app/front_end/src/features/editor/types/models/fileContentFilterModel.ts
  app/front_end/src/features/editor/types/models/fileContentModel.ts
Labels: feature, enhancement

#8 JTE/KFE-73
  app/front_end/src/features/editor/components/editorView/editorColumnMenu.tsx
  app/front_end/src/features/editor/components/editorView/editorColumnMenuAggregationItem.tsx
  app/front_end/src/features/editor/components/editorView/editorColumnMenuFilterItem.tsx
  app/front_end/src/features/editor/components/editorView/editorView.tsx
Labels: feature, enhancement

#9 MDE/KFE-71
  app/back_end/src/routes/workspace_route.py
  app/back_end/src/utils/helpers.py
  app/front_end/src/features/editor/components/editorView/editorColumnMenuFilterItem.tsx
  app/front_end/src/features/editor/components/editorView/editorView.tsx
  app/front_end/src/features/editor/types/models/fileContentAggregationModel.ts
Labels: feature, enhancement, refactor

#10 MDE/KBE-57
  app/back_end/src/data/constants.py
  app/back_end/src/data/downloading.py
  app/back_end/src/data/helpers.py
  app/back_end/src/data/refactoring.py
Labels: feature
