Repository mantvydasdeltuva/kath, pull requests merged in 2025-01, with the labels that each got.

#13 JTE/KFE-81
  app/front_end/src/features/editor/components/toolbarView/toolbarView.tsx
Labels: enhancement

#14 JTE/KFE-77
  app/front_end/src/components/dialogs/feedbackDialog/feedbackDialog.tsx
  app/front_end/src/components/dialogs/feedbackDialog/index.ts
  app/front_end/src/components/dialogs/feedbackDialog/textCopyArea.tsx
  app/front_end/src/components/dialogs/index.ts
  app/front_end/src/components/dialogs/settingsDialog/settingsFields/languageSetting.tsx
  app/front_end/src/components/dialogs/settingsDialog/settingsFields/timeZoneSetting.tsx
  app/front_end/src/components/layouts/baseLayout.tsx
  app/front_end/src/components/sidebar/sidebar.tsx
Labels: feature

#15 JTE/update/email
  app/front_end/src/components/dialogs/feedbackDialog/feedbackDialog.tsx
  app/front_end/src/components/dialogs/feedbackDialog/textCopyArea.tsx
Labels: enhancement

#16 MDE/KFE-74
  app/back_end/requirements.txt
  app/back_end/src/routes/workspace_merge_route.py
  app/front_end/src/features/editor/components/toolbarView/toolbarGroupButtons/downloadGroupButtons.tsx
  app/front_end/src/features/editor/components/toolbarView/toolbarGroupButtons/mergeGroupButtons.tsx
Labels: feature, enhancement

#17 JTE/KFE-82
  app/front_end/src/components/sidebar/sidebar.tsx
  app/front_end/src/types/constants/external_links.ts
  app/front_end/src/types/index.ts
Labels: feature

#18 VLE/KBE-61
  app/back_end/src/routes/workspace_merge_route.py
Labels: enhancement

#20 MDE/feature/custom-db
  app/back_end/src/routes/workspace_merge_route.py
  app/front_end/src/components/layouts/baseLayout.tsx
  app/front_end/src/features/editor/components/toolbarView/toolbarGroupButtons/mergeGroupButtons.tsx
  app/front_end/src/features/editor/components/toolbarView/toolbarGroupParams/mergeGroupParams.tsx
  app/front_end/src/features/editor/stores/toolbarContextProvider.tsx
Labels: enhancement

#19 MDE/feature/revel
  .gitignore
  app/back_end/README.md
  app/back_end/requirements.txt
  app/back_end/src/routes/workspace_apply_route.py
  app/back_end/src/scripts/revel.py
  app/back_end/src/tools/__init__.py
  app/back_end/src/tools/revel.py
  app/back_end/src/utils/logger.py
  app/front_end/src/features/editor/components/toolbarView/toolbarGroupButtons/applyGroupButtons.tsx
  tests/revel_test.ipynb
Labels: feature, enhancement

#21 VLE/KBE-60
  app/back_end/src/data/refactoring.py
  app/back_end/src/routes/workspace_merge_route.py
Labels: enhancement
